spring:
  application:
    name: maintenanceHospitalv1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maintenanceHospital?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123
  flyway:
    enabled: true # Garante que o Flyway está ativo
    baseline-on-migrate: true # Cria a tabela de histórico se ela não existir (evita erros na primeira execução)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Mostra no console o SQL que o Java está fazendo

